get:
  tags:
    - Attribute
  parameters:
    - name: attributeFQN
      in: path
      required: true
      schema:
        type: string
        nullable: true
    - name: value
      in: path
      required: true
      schema:
        type: string
        nullable: true
    - name: localeCode
      in: path
      required: true
      schema:
        type: string
        nullable: true
  responses:
    '200':
      description: Success
      content:
        application/json:
          schema:
            $ref: >-
              ../components/schemas/AttributeVocabularyValueLocalizedContent.yaml
        text/json:
          schema:
            $ref: >-
              ../components/schemas/AttributeVocabularyValueLocalizedContent.yaml
        text/plain:
          schema:
            $ref: >-
              ../components/schemas/AttributeVocabularyValueLocalizedContent.yaml
put:
  tags:
    - Attribute
  parameters:
    - name: attributeFQN
      in: path
      required: true
      schema:
        type: string
        nullable: true
    - name: value
      in: path
      required: true
      schema:
        type: string
        nullable: true
    - name: localeCode
      in: path
      required: true
      schema:
        type: string
        nullable: true
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/AttributeVocabularyValueLocalizedContent.yaml
  responses:
    '200':
      description: Success
      content:
        application/json:
          schema:
            $ref: >-
              ../components/schemas/AttributeVocabularyValueLocalizedContent.yaml
        text/json:
          schema:
            $ref: >-
              ../components/schemas/AttributeVocabularyValueLocalizedContent.yaml
        text/plain:
          schema:
            $ref: >-
              ../components/schemas/AttributeVocabularyValueLocalizedContent.yaml
delete:
  tags:
    - Attribute
  parameters:
    - name: attributeFQN
      in: path
      required: true
      schema:
        type: string
        nullable: true
    - name: value
      in: path
      required: true
      schema:
        type: string
        nullable: true
    - name: localeCode
      in: path
      required: true
      schema:
        type: string
        nullable: true
  responses:
    '200':
      description: Success
