type: object
properties:
  searchableInStorefront:
    type: boolean
    description: >-
      Indicates whether the attribute value should be searchable on the public
      storefront.
  searchableInAdmin:
    type: boolean
    description: >-
      Indicates whether the attribute value should be searchable in the merchant
      catalog admin.
  searchDisplayValue:
    type: boolean
    description: "If true, the system will index the display value of string attributes instead of the canonical value for searching. \r\nThe canonical value will always be used for filtering. Does not apply for for non-string attributes."
  allowFilteringAndSortingInStorefront:
    type: boolean
    description: >-
      Indicates whether the attribute should be able to be used in filters,
      facets, and sorting on the public storefront.
    nullable: true
  indexValueWithCase:
    type: boolean
    description: "Indicates whether the attribute value is case sensative for filtering and faceting. This applies to Text Admin entered attributes. \r\nA null value means it is not case sensative"
    nullable: true
  customWeightInStorefrontSearch:
    type: boolean
    description: >-
      Indicates whether the attribute is indevidually stored as a tokenized
      field in search for custom term search weight
    nullable: true
additionalProperties: false
description: >-
  Attribute Search Settings. A container for all of the search and indexing
  settings of an Attribute
