type: object
properties:
  productCode:
    type: string
    nullable: true
  purchaseLocation:
    type: string
    nullable: true
  fulfillmentTypesSupported:
    type: array
    items:
      type: string
    nullable: true
  variationProductCode:
    type: string
    nullable: true
  upc:
    type: string
    nullable: true
  mfgPartNumber:
    type: string
    nullable: true
  purchasableState:
    $ref: ./ProductPurchasableState.yaml
  priceRange:
    $ref: ./ProductPriceRange.yaml
  volumePriceBands:
    type: array
    items:
      $ref: ./ProductVolumePrice.yaml
    nullable: true
  volumePriceRange:
    $ref: ./ProductPriceRange.yaml
  price:
    $ref: ./ProductPrice.yaml
  availableShippingDiscounts:
    type: array
    items:
      $ref: ./Discount.yaml
    nullable: true
  measurements:
    $ref: ./PackageMeasurements.yaml
  inventoryInfo:
    $ref: ./ProductInventoryInfo.yaml
  options:
    type: array
    items:
      $ref: ./ProductOption.yaml
    nullable: true
  properties:
    type: array
    items:
      $ref: ./ProductProperty.yaml
    nullable: true
  priceListEntryTypeProperty:
    $ref: ./ProductProperty.yaml
  productImages:
    type: array
    items:
      $ref: ./ProductImage.yaml
    nullable: true
additionalProperties: false
