type: object
properties:
  productCode:
    type: string
    description: Product code of the product to discount.
    nullable: true
additionalProperties: false
description: Represents a product and quantity constraint
