type: object
properties:
  isoCurrencyCode:
    type: string
    description: Currency code.
    nullable: true
  cost:
    type: number
    description: Cost of the product. This is the price the merchant pays for the product.
    format: double
    nullable: true
additionalProperties: false
description: Price of the product and currency used.
