type: object
properties:
  customBoosts:
    type: array
    items:
      type: string
    nullable: true
  fieldValueBoost:
    $ref: ./FieldValueBoost.yaml
  searchChildProductsByDefault:
    type: boolean
  fieldWeights:
    type: array
    items:
      $ref: ./FieldWeight.yaml
    nullable: true
  personalizationExperience:
    type: string
    nullable: true
  personalizationFactor:
    type: number
    format: double
    nullable: true
  returnFields:
    type: array
    items:
      type: string
    nullable: true
additionalProperties: false
