required:
  - field
type: object
properties:
  field:
    type: string
    description: "The name of the field to sort on.\r\nMust be a known sort field or sortable attribute"
  direction:
    type: string
    description: ASC or DESC
    nullable: true
additionalProperties: false
