type: object
properties:
  isoCurrencyCode:
    type: string
    description: Currency code.
    nullable: true
  price:
    type: number
    description: >-
      Price of the product. This is the price the merchant intends to sell the
      product if no sale price is present.
    format: double
    nullable: true
  salePrice:
    type: number
    description: >-
      Current sale price of the product. Sale price is a numeric (monetary)
      amount, not a percentage off.
    format: double
    nullable: true
  msrp:
    type: number
    description: Manufacturer Suggested Retail Price. +
    format: double
    nullable: true
  map:
    type: number
    description: Minimum Advertised Price
    format: double
    nullable: true
  mapStartDate:
    type: string
    description: Minimum Advertised Price effective start date (null = begining of time)
    format: date-time
    nullable: true
  mapEndDate:
    type: string
    description: Minimum Advertised Price effectivity end date (null = forever)
    format: date-time
    nullable: true
  creditValue:
    type: number
    description: Credit amt of the product
    format: double
    nullable: true
additionalProperties: false
description: Price of the product and currency used.
