type: object
properties:
  manageStock:
    type: boolean
    description: 'If true, the Products service manages inventory for this product.'
    nullable: true
  outOfStockBehavior:
    type: string
    description: The behvior when the ManageStock is true and the product is not in stock.
    nullable: true
additionalProperties: false
description: >-
  Use the Products resource to create and manage products for your store. You
  can create products with options that a shopper configures (such as a T-shirt
  color and size). The system can manage inventory for all combinations of your
  product options, and can calculate tax and shipping costs.
