type: object
properties:
  value:
    type: object
    additionalProperties: false
    nullable: true
  content:
    $ref: ./ProductPropertyValueLocalizedContent.yaml
  localizedContent:
    type: array
    items:
      $ref: ./ProductPropertyValueLocalizedContent.yaml
    nullable: true
  attributeVocabularyValueDetail:
    $ref: ./AttributeVocabularyValue.yaml
additionalProperties: false
description: >-
  A value of a product option for this product. For example, a computer product
  may have an option called "Memory" that can have the values "6GB,"8GB," and
  "12GB."
