type: object
properties:
  publishedState:
    type: string
    nullable: true
  lastPublishedBy:
    type: string
    nullable: true
  lastPublishedDate:
    type: string
    format: date-time
    nullable: true
  publishSetCode:
    type: string
    nullable: true
additionalProperties: false
description: Price of the product and currency used.
